env:
  es2021: true
  node: true
  jest/globals: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'jest'
rules: {"import/extensions": "off"}
settings:
  import/parsers:
    '@typescript-eslint/parser': [ .ts, .tsx ]
  import/resolver:
    node:
      extensions: [".js", ".jsx", ".ts", ".tsx"]
